
language: java
jdk:
  - oraclejdk8
services:
  - mongodb
before_script:
  - "export DISPLAY=:99.0"
  - "Xvfb -ac :99 -screen 0 1280x1024x16 &"
  - sleep 3 # give xvfb some time to start
addons:
    firefox: "45.0.2"